#!/bin/sh
ROOT=$(dirname "$0")
ROOT=$(dirname "$ROOT")
ROOT=$(dirname "$ROOT")
echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="./vendor/bin/php-cs-fixer"
EXEC_PHP="symfony php"
HAS_PHP_CS_FIXER=false
if [ -x  "$PHP_CS_FIXER" ]; then
    HAS_PHP_CS_FIXER=true
else
    echo "PHP CS Fixer not installed into $PHP_CS_FIXER"
fi
if [ -f "$ROOT/.php-cs-fixer.php" ]; then
    echo "PHP CS Fixer config file found in projet"
    PHP_CS_CONFIG=".php-cs-fixer.php"
fi
if [ "x$PHP_CS_CONFIG" = "x" ]; then
    echo "No PHP CS Fixer config file found !"
    HAS_PHP_CS_FIXER=false
fi
if $HAS_PHP_CS_FIXER; then
  CHANGED_FILES=$(git status --porcelain --untracked-files=all | grep '^[AMDR]' | grep -e '^[ AM]\(.*\).php$' | cut -c 3-)
  $EXEC_PHP $PHP_CS_FIXER fix --config=$ROOT/$PHP_CS_CONFIG --verbose --path-mode=intersection ${CHANGED_FILES};
  for line in ${CHANGED_FILES}
  do
      git add "$line";
  done
else
    echo ""
    echo "Please install php-cs-fixer:"
    echo ""
    echo "Use composer install"
    echo ""
fi
echo "php-cs-fixer pre commit hook finish"
