#!/usr/bin/env php
<?php

namespace Farmitoo\ReplibyteBundle\Tests\App;

require_once __DIR__ . '/../../vendor/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$_SERVER['APP_RUNTIME_OPTIONS']['dotenv_path'] = './.env';
$kernel = new AppKernel('dev', true);
$application = new Application($kernel);
$application->run();
