#!/usr/bin/env php
<?php

namespace Farmitoo\ReplibyteBundle\Tests\App;

require_once __DIR__ . '/../../vendor/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

(new Dotenv())->load(__DIR__.'/.env');
$kernel = new AppKernel('dev', true);
$application = new Application($kernel);
$application->run();
